version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  bot:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./:/code
    depends_on:
      - postgres

volumes:
  pgdata:
