version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  bot:
    depends_on:
      - db
    build:
      context: ./bot
    image: discord_soundboard_bot:${TAG}
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@db:5432/postgres
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NODE_ENV=production

volumes:
  pgdata:
