version: "3.8"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgres

  # player:
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./player/src:/player/src

  bot:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - NODE_ENV=development
    volumes:
      - ./bot/src:/bot/src
